baseURL = 'https://www.alfa-betta.be/'
languageCode = 'nl-BE'
title = 'Alfa-Betta.be'
theme = 'AB_Official'
paginate = 4
enableRobotsTXT = true

[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.tableOfContents]
          endLevel = 4
          ordered = false
          startLevel = 3

[params]
    description = "alfa-betta, een blog site over het houden van betta splendens en meer. gebouwd en onderhouden door een vlaams aquariaan, gefascineerd door betta splendens!"
    author = "Steven Sambalii"
    authorImage = "/images/author_icon.png"

[permalinks]
    blog = "/:filename"

# .hoofd website menu

[[menu.main]]
    name = "Algemeen"
    url = "/blog"
    weight = 10

[[menu.main]]
    name = "Verzorging"
    url = "/categories/verzorging"
    weight = 20

[[menu.main]]
    name = "Weetjes"
    url = "/categories/weetjes"
    weight = 30

[[menu.main]]
    name = "Alle Onderwerpen"
    url = "/categories"
    weight = 100

# /.hoofd website menu

# .social items

#[[menu.social]]
#    name = "youtube"
#    url = "https://www.youtube.com"
 #   pre = "<i class='fa-brands fa-square-youtube fa-2xl'></i>"

[[menu.social]]
    name = "facebook"
    url = "https://www.facebook.com/profile.php?id=100085753795043"
    pre = "<i class='fa-brands fa-square-facebook fa-2xl'></i>"

# /.social items

# .footer links

[[menu.footer]]
    name = "Cookie Beleid"
    url = "/cookiebeleid"

# gerelateerd

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categoriën"
        weight = 100

    [[related.indices]]
        name = "datum"
        weight = 10

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[params.shareButtons]
  networks = [ "facebook", "twitter", "email", "reddit", "pinterest", "reddit", "whatsapp" ]
  size = "medium"
  icon = "solid"
  buttonMargin = "0.2em"